### ISSUE TITLE
traceback when message received

### ISSUE THREAD

**Issue by Jajcus** [Jajcus/cjc#23]
I sometimes get the following traceback when a message is received and I never see the message.

{{{
[20:07] Other error cought
[20:07] Exception:
Traceback (most recent call last):
  File "/usr/local/share/cjc/cjc/main.py", line 1382, in stream_loop
    act = self.stream.loop_iter(1)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 598, in loop_iter
    return self._loop_iter(timeout)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 616, in _loop_iter
    self._process()
  File "/usr/src/pyxmpp/tests/pyxmpp/streamtls.py", line 178, in _process
    StreamBase._process(self)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 637, in _process
    self._read()
  File "/usr/src/pyxmpp/tests/pyxmpp/streamtls.py", line 173, in _read
    StreamBase._read(self)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 661, in _read
    self._feed_reader(r)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 677, in _feed_reader
    r=self._reader.feed(data)
  File "/usr/src/pyxmpp/tests/pyxmpp/xmlextra.py", line 537, in feed
    return self.reader.feed(s)
  File "/usr/src/pyxmpp/tests/pyxmpp/xmlextra.py", line 57, in _stanza
    self.stanza(doc,node)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 401, in stanza
    self._process_node(node)
  File "/usr/src/pyxmpp/tests/pyxmpp/stream.py", line 107, in _process_node
    StreamBase._process_node(self,xmlnode)
  File "/usr/src/pyxmpp/tests/pyxmpp/streambase.py", line 710, in _process_node
    self.process_stanza(stanza)
  File "/usr/src/pyxmpp/tests/pyxmpp/stanzaprocessor.py", line 268, in process_stanza
    if self.process_message(stanza):
  File "/usr/src/pyxmpp/tests/pyxmpp/stanzaprocessor.py", line 203, in process_message
    return self.__try_handlers(self._message_handlers,"normal",stanza)
  File "/usr/src/pyxmpp/tests/pyxmpp/stanzaprocessor.py", line 179, in __try_handlers
    response = handler(stanza)
  File "/usr/local/share/cjc/plugins/message.py", line 558, in message_normal
    buff=self.find_or_make(fr,thread)
  File "/usr/local/share/cjc/plugins/message.py", line 520, in find_or_make
    cjc_globals.screen.display_buffer(buff)
  File "/usr/local/share/cjc/cjc/ui/screen.py", line 316, in display_buffer
    if buffer.window:
AttributeError: MessageBuffer instance has no attribute 'window'
}}}

This seems to be an intermittent problem which mostly occurs when I receive a message from someone for the first time after connecting to the server.  And the problem only seems to occur with messages, not with chats.

A possibly related issue is that setting message.autopopup seems to have no effect.  When I do actually receive a message I have to switch to the message window even if message.autopopup is true.

**Comment by Jajcus** [comment]
Just a few more details on the message traceback.

The traceback only occurs when message.autopopup is true and only the first time a message is received after cjc has been started.  If message.autopopup is false, this traceback doesn't occur at all until message.autopopup is set to true.

--lorenzo@taylor.homelinux.net

**Comment by Jajcus** [comment]
(In [670]) - when auto_popup is on display actual buffer instead of MessageBuffer (I know, this class name sucks). fixes #23

--jajcus
