### ISSUE TITLE
Incompatible with M2Crypto 0.16

### ISSUE THREAD

**Issue by Jajcus** [Jajcus/cjc#29]
Subj. Same with 1.0.0 and r675 from trunk:

sat@thror:/home/sat/bsdevel/ports/net-im/cjc/work/cjc-1.0.0.675# ./cjc.py
Traceback (most recent call last):
  File "./cjc.py", line 64, in ?
    from cjc import main
  File "/usr/home/sat/bsdevel/ports/net-im/cjc/work/cjc-1.0.0.675/cjc/main.py", line 36, in ?
    import pyxmpp.all
  File "/usr/local/lib/python2.4/site-packages/pyxmpp/all.py", line 33, in ?
    from pyxmpp.stream import Stream
  File "/usr/local/lib/python2.4/site-packages/pyxmpp/stream.py", line 30, in ?
    from pyxmpp.streamtls import StreamTLSMixIn
  File "/usr/local/lib/python2.4/site-packages/pyxmpp/streamtls.py", line 37, in ?
    from M2Crypto import SSL
  File "/usr/local/lib/python2.4/site-packages/M2Crypto/**init**.py", line 16, in ?
    import ASN1
  File "/usr/local/lib/python2.4/site-packages/M2Crypto/ASN1.py", line 18, in ?
    class ASN1_Integer:
  File "/usr/local/lib/python2.4/site-packages/M2Crypto/ASN1.py", line 20, in ASN1_Integer
    m2_asn1_integer_free = m2.asn1_integer_free
AttributeError: 'module' object has no attribute 'asn1_integer_free'

Thanks!

**Comment by Jajcus** [comment]
It seems like a problem in M2Crypto, not CJC/PyXMPP. It seems M2Crypto was compiled or installed wrong, or there is some conflict with other M2Crypto version installed.

--jajcus

**Comment by Jajcus** [comment]
There is a problem with the m2crypto port found on *BSD.  For some reason,  the asn1 module is not included. You can remove the file ports/py-m2crypto/files/patch-SWIG::_m2crypto.i and reinstall the m2crypto port.  I'm not sure why the line to include the _asn.i module was commented out, but m2crypto works after you take out that change.

--jdarnold@buddydog.org

**Comment by Jajcus** [comment]
M2Crypto is not used any more.

--jajcus
