### ISSUE TITLE
cjc error

### ISSUE THREAD

**Issue by Jajcus** [Jajcus/cjc#31]
[10:55] Presence error from: dzemik@jabber.pcmedia.com.pl: Service is not available
[10:55] Exception:
Traceback (most recent call last):
  File "/home/users/agaran/cjc/cjc/main.py", line 331, in send_event
    h(event,arg)
  File "/home/users/agaran/cjc/plugins/roster.py", line 107, in ev_presence_changed
    self.update_item(arg)
  File "/home/users/agaran/cjc/plugins/roster.py", line 136, in update_item
    self.write_item(None,item)
  File "/home/users/agaran/cjc/plugins/roster.py", line 244, in write_item
    self.buffer.insert_themed((group,params["jid"]),"roster.unavailable",params)
  File "/home/users/agaran/cjc/cjc/ui/list_buffer.py", line 128, in insert_themed
    for attr,s in cjc_globals.theme_manager.format_string(format,params):
  File "/home/users/agaran/cjc/cjc/themes.py", line 280, in format_string
    return self.do_format_string(format,"default",params)
  File "/home/users/agaran/cjc/cjc/themes.py", line 342, in do_format_string
    ret+=self.do_format_string(next,next_attr,params)
  File "/home/users/agaran/cjc/cjc/themes.py", line 331, in do_format_string
    s=self.substitute(format,params)
  File "/home/users/agaran/cjc/cjc/themes.py", line 358, in substitute
    format=self.process_format_param(format,key,params)
  File "/home/users/agaran/cjc/cjc/themes.py", line 489, in process_format_param
    err=pr.get_error()
  File "/home/users/agaran/cjc/pyxmpp/pyxmpp/stanza.py", line 221, in get_error
    raise ProtocolError, (None, "This stanza contains no error: %r" % (self.serialize(),))
ProtocolError: This stanza contains no error: '<presence xmlns="jabber:client" to="agaran@pld-linux.org/cjc1" type="error" from="dzemik@jabber.pcmedia.com.pl"><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error><priority>-10</priority></presence>'
[10:55] Event handler failed

**Comment by Jajcus** [comment]
a wyglada ze po kazdym presence error dostaje taki traceback..

--anonymous

**Comment by Jajcus** [comment]
Probably already fixed.

--jajcus
