### ISSUE TITLE
CJC does not Run ? ( i am a python beginner)

### ISSUE THREAD

**Issue by Jajcus** [Jajcus/cjc#37]
I installed pyxmpp 1.0 in my /usr/local
then installed cjc 1.0 in samme /usr/local
it installed sucessfully.
But when i ran cjc the follwing exception was generated :

Traceback (most recent call last):
  File "/usr/local/bin/cjc", line 13, in <module>
    from cjc import main
  File "/usr/local/share/cjc/cjc/main.py", line 36, in <module>
    import pyxmpp.all
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/all.py", line 33, in <module>
    from pyxmpp.stream import Stream
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/stream.py", line 29, in <module>
    from pyxmpp.streambase import StreamBase
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/streambase.py", line 47, in <module>
    from pyxmpp import resolver
  File "/usr/local/lib/python2.5/site-packages/pyxmpp/resolver.py", line 30, in <module>
    import dns.resolver
ImportError: No module named dns.resolver

Tell me if any other module is required too ?

**Comment by Jajcus** [comment]
CJC won't start if PyXMPP requirements (described in the PyXMPP README file) are not met.

In this case [http://www.dnspython.org/ dnspython] is missing.

--http://openid.jajcus.net/jajcus/
