### ISSUE TITLE
unsetting presence.auto_away -> exception

### ISSUE THREAD

**Issue by Jajcus** [Jajcus/cjc#38]
Help for presence.auto_away says: Time in minutes after set presence should be set to 'away' (unset or 0 to disable)

When using /unset presence.auto_away I get loads of this exception:

{{{
[03:00] Exception:
Traceback (most recent call last):
  File "/<foo>/cjc/cjc/main.py", line 331, in send_event
    h(event,arg)
  File "/<foo>/cjc/plugins/presence.py", line 159, in ev_idle
    auto_away=self.settings["auto_away"]
KeyError: 'auto_away'
[03:00] Event handler failed
}}}

svn version:
- Repository Root: http://cjc.jajcus.net/svn/cjc
- Revision: 679

Setting presence.auto_away to 0 works fine

**Comment by Jajcus** [comment]
(In [692]) - use get() to read optional settings (fixes #38)

--jajcus
